### ISSUE TITLE
New NPM Release

### ISSUE THREAD

**Issue by SamPlacette** [jasnell/http-problem#2]
Hi @jasnell, I see you have approved the PR I sent, thank you. Could you please merge and release to NPM? As the project maintainer only you can perform the merge and NPM release.

Thank you
Sam

**Comment by jasnell** [comment]
Yeah, been a bit buried this week on other items. I'l be merging it in and cutting a new release by tomorrow

**Comment by SamPlacette** [comment]
Sounds good. Hope your other commitments are going well. Thanks!

**Comment by SamPlacette** [comment]
Hi @jasnell, would you consider making me a contributor to this project? I have found it very useful and I would like to continue maintaining and using it in my projects.

Thanks!
Sam

**Comment by jasnell** [comment]
new version published. I can add you, just need to first confirm that you agree that contributions are under the Apache 2.0 license.

**Comment by SamPlacette** [comment]
Thanks!

I agree that any and all contributions I make to the project are under the Apache 2.0 license.
